version: 0.0
os: t2.micro
files:
  - source: /todolist.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: deploy/before_install
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy/restart_server
      timeout: 300
      runas: root
