version: '3'
services:
        docker-mysql:
                image: mysql
                container_name: docker-mysql
                restart: always
                expose:
                        - 3306
                environment:
                        MYSQL_ROOT_PASSWORD: root
                        MYSQL_PASSWORD: root
                        MYSQL_USER: root
                        MYSQL_DATABASE: jwt_db
        gradle-container:
                image: phamed/todorepo:first
                container_name: todorepo
                restart: always
                environment:
                        DB NAME: jwt_db
                        SPRING_DATASOURCE_USERNAME: root
                        SPRING_DATASOURCE_PASSWORD: root
                        APP_PORT: 8080
                depends_on:
                        - docker-mysql
                ports:
                        - 8080:8080
                tty: true
