version: '3'
services:
        docker-mysql:
                image: mysql
                container_name: docker-mysql
                restart: always
                expose:
                        - 3306
                environment:
                        MYSQL_ROOT_PASSWORD: root
                        MYSQL_PASSWORD: root
                        MYSQL_DATABASE: jwt_db
        gradle-container:
                image: greenfox/todo
                container_name: todo-container
                restart: always
                environment:
                        DB_URL: jdbc:mysql://docker-mysql/jwt_db
                        DB_USERNAME: root
                        DB_PASSWORD: root
                        APP_PORT: 8080
                        JWT_SECRET: secret
                        TOKEN_PREFIX: Bearer
                        HEADER_STRING: Authorization
                depends_on:
                        - docker-mysql
                ports:
                        - 8080:8080
                tty: true
